version: "3.9"

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit
    restart: always  # コンテナが停止した時に常に再起動する設定
    expose:
      # コンテナ側のポート
      # https://tkzo.jp/blog/difference-between-ports-and-expose-in-docker-compose/
      - "8060"
    ports:
      # アクセスIP(ここでは127.0.0.1なのでローカルループバックアドレス)からのみ8050ポートへの接続が許可され，コンテナ側の8050ポートへの接続が許可される
      # https://tkzo.jp/blog/difference-between-ports-and-expose-in-docker-compose/
      - "127.0.0.1:8060:8060"
    volumes:
      - "../src/:/root/src/"
      - "../credentials_oauth.json:/root/credentials_oauth.json"
